"""Added timestamp field

Revision ID: 500ba42e3bed
Revises: 
Create Date: 2025-03-11 22:16:17.789117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500ba42e3bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
