"""Removed new_column from User model

Revision ID: 78c9c58619ae
Revises: 01c38b9b6f61
Create Date: 2025-03-12 07:06:24.184024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9c58619ae'
down_revision = '01c38b9b6f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', 'user',['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email' ,type_='unique')
        batch_op.drop_column('email')
        

    # ### end Alembic commands ###
